//
//  DetailsInteractor.swift
//  marvelHeroes
//
//  Created by Rodrigo Conte on 01/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsBusinessLogic {
    func requestCharacter()
    func requestImage()
    func saveCharacterInFavorite()
    func removeCharacterFromFavorite()
}

protocol DetailsDataStore {
    var character: CharacterModel? { get set }
}

class DetailsInteractor: DetailsBusinessLogic, DetailsDataStore {
    
    var presenter: DetailsPresentationLogic?
    var worker = DetailsWorker()
    
    // MARK: Data Store
    
    var character: CharacterModel?
    
    // MARK: Business Logic
    
    func requestCharacter() {
        guard
            let character = character,
            let id = character.id
        else {
            presenter?.presentError(.unexpectedError)
            return
        }
        
        worker.getFavoriteCharacter(withId: id) { (result) in
            switch result {
            case .success(let favoritesCharacter):
                let response = Details.Character.Response(character: character, favoriteCharacter: favoritesCharacter.first)
                presenter?.presentCharacter(response: response)
            case .failure:
                presenter?.presentError(.database)
            }
        }
    }
    func requestImage() {
        guard
            let path = character?.thumbnail?.path,
            let extensionType = character?.thumbnail?.extension,
            let url = URL(string: path + "." + extensionType)
        else {
            presenter?.presentError(.unexpectedError)
            return
        }
        
        worker.requestImage(fromURL: url) { [weak self] (result) in
            guard let self = self else { return }
            
            switch result {
            case .success(let image):
                let response = Details.GetImage.Response(image: image)
                self.presenter?.presentImage(response: response)
            case .failure(let error):
                self.handleRequestImageError(error: error)
            }
        }
    }
    
    func saveCharacterInFavorite() {
        guard let name = character?.name, let id = character?.id else {
            self.presenter?.presentError(.unexpectedError)
            return
        }
        
        worker.saveCharacterOnFavorite(name: name, id: id) { [weak self] (error) in
            guard let self = self else { return }
            if error == nil {
                self.presenter?.presentDatabaseSuccess()
            } else {
                self.presenter?.presentError(.database)
            }
        }
    }
    
    func removeCharacterFromFavorite() {
        guard let id = character?.id else {
            presenter?.presentError(.unexpectedError)
            return
        }
        
        worker.removeCharacterFromFavorite(id: id) { [weak self] (error) in
            guard let self = self else { return }
            if error == nil {
                self.presenter?.presentDatabaseSuccess()
            } else {
                self.presenter?.presentError(.database)
            }
        }
    }
    
    // MARK: Private Functions
    
    func handleRequestImageError(error: Error) {
        let nsError = error as NSError
        if nsError.code  == NSURLErrorNotConnectedToInternet {
            presenter?.presentError(.notConnectedToInternet)
        } else {
            presenter?.presentError(.unexpectedError)
        }
    }
    
}
