//
//  DetailsPresenter.swift
//  marvelHeroes
//
//  Created by Rodrigo Conte on 01/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsPresentationLogic {
    func presentCharacter(response: Details.Character.Response)
    func presentImage(response: Details.GetImage.Response)
    func presentDatabaseSuccess()
    func presentError(_ error: Details.Error)
}

class DetailsPresenter: DetailsPresentationLogic {
    
    weak var viewController: DetailsDisplayLogic?
    
    // MARK: Presentation Logic
    
    func presentCharacter(response: Details.Character.Response) {
        let name = response.character.name ?? "-"
        let isFavorited = response.favoriteCharacter != nil
        let description = response.character.description ?? "-"
        let viewModel = Details.Character.ViewModel(name: name, description: description, isFavorited: isFavorited)
        viewController?.displayCharacter(viewModel: viewModel)
    }
    
    func presentImage(response: Details.GetImage.Response) {
        let viewModel = Details.GetImage.ViewModel(image: response.image)
        viewController?.displayImage(viewModel: viewModel)
    }
    
    func presentDatabaseSuccess() {
        viewController?.displayDatabaseSuccess()
    }
    
    func presentError(_ error: Details.Error) {
        viewController?.displayError(error)
    }
}
