//
//  DetailsModels.swift
//  marvelHeroes
//
//  Created by Rodrigo Conte on 01/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Details {
    
    // MARK: Use cases
    
    enum Character {
        struct Response {
            let character: CharacterModel
            let favoriteCharacter: FavoriteEntity?
        }
        struct ViewModel {
            let name: String
            let description: String
            var isFavorited: Bool
        }
    }
    
    enum GetImage {
        struct Response {
            let image: UIImage
        }
        struct ViewModel {
            let image: UIImage
        }
    }
    
    enum Error {
        case unexpectedError
        case database
        case notConnectedToInternet
        
        var message: String {
            switch self {
            case .unexpectedError:
                return ErrorConstants.unexpectedError
            case .database:
                return ErrorConstants.database
            case .notConnectedToInternet:
                return ErrorConstants.notConnectedToInternet
            }
        }
    }
}
