//
//  CharactersModels.swift
//  marvelHeroes
//
//  Created by Rodrigo Conte on 31/01/21.
//  Copyright (c) 2021 Rodrigo Conte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Characters
{
  // MARK: Use cases
  
  enum GetCharacter {
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
    }
  }
}
