//
//  CharactersInteractor.swift
//  marvelHeroes
//
//  Created by Rodrigo Conte on 31/01/21.
//  Copyright (c) 2021 Rodrigo Conte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharactersBusinessLogic {
  func doSomething(request: Characters.GetCharacter.Request)
}

protocol CharactersDataStore {
  //var name: String { get set }
}

class CharactersInteractor: CharactersBusinessLogic, CharactersDataStore {
  var presenter: CharactersPresentationLogic?
  var worker: CharactersWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Characters.GetCharacter.Request) {
    worker = CharactersWorker()
    worker?.doSomeWork()
    
    let response = Characters.GetCharacter.Response()
    presenter?.presentSomething(response: response)
  }
}
