//
//  CharactersRouter.swift
//  marvelHeroes
//
//  Created by Rodrigo Conte on 31/01/21.
//  Copyright (c) 2021 Rodrigo Conte. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CharactersRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CharactersDataPassing
{
  var dataStore: CharactersDataStore? { get }
}

class CharactersRouter: NSObject, CharactersRoutingLogic, CharactersDataPassing
{
  weak var viewController: CharactersViewController?
  var dataStore: CharactersDataStore?
  
}
