//
//  FavoritesModels.swift
//  marvelHeroes
//
//  Created by Rodrigo Conte on 01/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Favorites {
    
    // MARK: Use cases
    
    enum GetFavorites {
        struct Response {
            let favorites: [FavoriteEntity]
        }
        struct ViewModel {
            let names: [String]
        }
    }
    
    enum RemoveFromDatabase {
        struct Request {
            let indexPath: IndexPath
        }
        struct Response {
            let indexPath: IndexPath
        }
        struct ViewModel {
            let indexPath: IndexPath
        }
    }
    
    enum Error {
        case database
        case emptyList
        
        var message: String {
            switch self {
            case .database:
                return ErrorConstants.database
            case .emptyList:
                return "Não há nenhum personagem na lista de favoritos"
            }
        }
    }
}
